### ISSUE TITLE
release for python 3

### ISSUE THREAD

**Issue by spereverde** [collective/Products.PloneLDAP#11]
Just to ask, I see a lot of changes since the last release, including for python 3 
The last release (1.2) dates back to 2012
Is there any plan for a new release?
We would be very interested :-)

**Comment by ale-rt** [comment]
Hi @spereverde, I am just leaving some notes so you can take an informed decision.

I did some of the commits you mention.
Anyway, I cannot tell you how good the master branch is working with a recent Plone/Python combo.
Like the majority of the developers I know, I moved since quite some years to https://github.com/collective/pas.plugins.ldap.

**Comment by spereverde** [comment]
thanks for the info!
we're migrating to plone 5 still, but haven't had the time/guts to do the full refactoring for LDAP since our setup has been working so long with this package, it does seem to work well so far in a Plone 5.2 setup (in test, not on production yet)
But I might check that solution, it seems it also has better genericsetup support, since we're also still using vs.genericsetup.ldap and I remember reading that pas.plugins.ldap has better integration for that as well

**Comment by albertduran** [comment]
Hi @ale-rt, I'm just checking the last comments and I've tried [https://github.com/collective/pas.plugins.ldap](https://github.com/collective/pas.plugins.ldap) but it don't works fine in my plone 6 instalation. My ldap is very big and I've seen that pas.plugins.ldap tries to cache the whole ldap.

Anyway, I tried this package and works for me... is there any plan for a new release?

Thank you very much for your work

**Comment by ale-rt** [comment]
@albertduran interesting!
It would be nice to report back the issues you found here: https://github.com/collective/pas.plugins.ldap/issues
(if you have not done it already).

BTW, I have no power on releasing this package.
Maybe @mauritsvanrees could release an alpha version?

**Comment by rnixx** [comment]
@albertduran

> My ldap is very big and I've seen that pas.plugins.ldap tries to cache the whole ldap.

This is a known tradeoff and will be fixed as soon as there is a proper project/proper funding.

**Comment by mauritsvanrees** [comment]
I have released 2.0.0a1:
https://pypi.org/project/Products.PloneLDAP/2.0.0a1/
I think anyone who still uses this product should feel free to create PRs to drop Plone 5.1 and earlier, and Python 2.  But I am not using it anymore.

I have made the collective user owner on PyPI.
